import { Inter } from 'next/font/google'
import './globals.css'
import "bootstrap/dist/css/bootstrap.css";
import Head from 'next/head';
import Navbar_basic from './_componenets/Navbar';
import { MyProvider } from './_Handlers/Mycontext';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Symptoms Monitoring',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <MyProvider>
        <body className={inter.className}>
          <main className="h-screen flex flex-col justify-center items-center">
            <Navbar_basic />
            <div className='container' style={{ marginTop: '60px' }} >
              {children}
            </div>
          </main>
        </body>
      </MyProvider>
    </html>
  )
}



